name: mAntiESP
version: '${project.version}'
main: dev.murk.antiesp.MAntiESP
api-version: '1.16'
author: Murk
description: 'AntiESP'
depend: [packetevents]

commands:
  mantiesp:
    description: Main command for mAntiESP
    permission: mantiesp.admin
    usage: /mantiesp reload

permissions:
  mantiesp.admin:
    description: Allows reloading and managing mAntiESP
    default: op
